# Utilise une image officielle MySQL comme base
FROM mysql:latest

# Définir les variables d'environnement
ENV MYSQL_ROOT_PASSWORD=root_password   # Mot de passe root MySQL
ENV MYSQL_DATABASE=example_db           # Base de données initiale à créer
ENV MYSQL_USER=user                     # Utilisateur MySQL
ENV MYSQL_PASSWORD=user_password        # Mot de passe de l'utilisateur

# Copier un fichier SQL pour initialiser la base de données
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Expose le port MySQL
EXPOSE 3306

# Commande pour démarrer MySQL (elle est déjà incluse dans l'image MySQL officielle)
CMD ["mysqld"]
